version: "3.9"

services:
  web:
    build: .
    container_name: cybercampus_web
    # Écoute uniquement en local pour Nginx
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: cybercampus_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # La BDD n'est jamais exposée à l'extérieur
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cybercampus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # Gardé ouvert pour ton accès admin (à sécuriser via Firewall Cloud)
    ports:
      - "5050:80"
    depends_on:
      - db

  sqli-challenge:
    build: ./challenges/sqli
    container_name: cybercampus_sqli
    ports:
      - "127.0.0.1:5001:5001"
    restart: always

  xss-challenge:
    build: ./challenges/xss
    container_name: cybercampus_xss
    ports:
      - "127.0.0.1:5002:5002"
    restart: always

  bruteforce-challenge:
    build: ./challenges/bruteforce
    container_name: cybercampus_bruteforce
    ports:
      - "127.0.0.1:5004:5004"
    restart: always
    
  crypto-challenge:
    build: ./challenges/crypto
    container_name: cybercampus_crypto
    ports:
      - "127.0.0.1:5003:5003"
    restart: always

  osint-challenge:
    build: ./challenges/osint
    container_name: cybercampus_osint
    ports:
      - "127.0.0.1:5005:5005"
    restart: always 

  upload-challenge-image:
    build: ./challenges/upload/challenge
    image: upload-challenge:latest
    command: "true" 
    restart: "no"

  upload-challenge:
    build: ./challenges/upload/launcher
    container_name: cybercampus_upload
    ports:
      - "127.0.0.1:5006:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - upload-challenge-image
    restart: unless-stopped

volumes:
  pgdata:
